---
:hardlink: true
:hardlink_dir: '/mirror'
:all: true
:all_name: 'all'
:datestamp_all: true
:mirror_base: '/mirror'
:mirrors:
  os:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/7/os/x86_64/'
  extras:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/7/extras/x86_64/'
  plus:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/7/centosplus/x86_64/'
  updates:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/7/updates/x86_64/'
  scl:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/7/sclo/x86_64/rh/'
  epel:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://mirror.us.leaseweb.net/epel/7/x86_64/'
  pc1:
    :dist: 'centos-7-x86_64'
    :type: 'rsync'
    :url: 'rsync://yum.puppetlabs.com/packages/yum/el/7/PC1/x86_64/'
